version: '3.0'
services:
  dev-database:
    image: postgres:15.3
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123456
      POSTGRES_DB: lostandfound

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: development
    command: npm run dev
    env_file:
      - ./server/.env
    depends_on:
      - dev-database
    volumes:
      - .:/server/
      - /server/node_modules
    ports:
      - '8000:8000'